#include "field1.h"

const int FIELD1_DATA[FIELD1_HEIGHT][MAP_W] = {
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL}
};


const SpawnData FIELD1_SPAWNS[] = {
    {SPAWN_DOOR, 4, 0, 0, 0, 0, 6},
    {SPAWN_DOOR, 8, 2, 0, 0, 0, 0},
    {SPAWN_KEY, 2, 2, 1, 0, 0, 0},
    {SPAWN_BOMB, 6, 2, 1, 0, 0, 0},
    {SPAWN_POTION, 4, 3, 2, 0, 0, 0},
};
const int FIELD1_SPAWN_COUNT = (int)(sizeof(FIELD1_SPAWNS) / sizeof(FIELD1_SPAWNS[0]));
