#include "field1.h"

const int FIELD1_DATA[FIELD1_HEIGHT][MAP_W] = {
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL}
};


const SpawnData FIELD1_SPAWNS[] = {
    {SPAWN_DOOR, 4, 0, 0, 0, 0, 6},
    {SPAWN_DOOR, 8, 2, 0, 0, 0, 0},
    {SPAWN_KEY, 2, 2, 1, 0, 0, 0},
    {SPAWN_BOMB, 1, 2, 1, 0, 0, 0},
    {SPAWN_OBSTACLE, 3, 2, OBSTACLE_TREE, 1, 0, 0},
    {SPAWN_OBSTACLE, 4, 2, OBSTACLE_ICE_WALL, 1, 1, 0},
    {SPAWN_POTION, 4, 3, 2, 0, 0, 0},
    {SPAWN_BOX, 2, 1, BOX_CONTENT_KEY, 1, 0, 0},
    {SPAWN_BOX, 3, 1, BOX_CONTENT_POTION, 1, 0, 0},
    {SPAWN_BOX, 4, 1, BOX_CONTENT_BOMB, 1, 0, 0},
    {SPAWN_BOX, 5, 1, BOX_CONTENT_TRAP, 1, 0, 0},
    {SPAWN_BOX, 6, 1, BOX_CONTENT_EMPTY, 1, 0, 0},
    {SPAWN_BOX, 7, 1, BOX_CONTENT_RANDOM, 1, 0, 0},
    {SPAWN_ENEMY_SNAKE, 6, 3, 0, 0, 0, 0},
    {SPAWN_ENEMY_SNAKE, 7, 4, 0, 0, 0, 0},
};
const int FIELD1_SPAWN_COUNT = (int)(sizeof(FIELD1_SPAWNS) / sizeof(FIELD1_SPAWNS[0]));
