#include "field2.h"

const int FIELD2_DATA[FIELD2_HEIGHT][MAP_W] = {
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_EMPTY, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_EMPTY},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL}
};


const SpawnData FIELD2_SPAWNS[] = {
    {SPAWN_DOOR, 5, 0, 0, 0, 0, 7},
    {SPAWN_DOOR, 0, 2, 0, 0, 0, 0},
    {SPAWN_DOOR, 10, 2, 0, 0, 0, 1},
    {SPAWN_BOMB, 5, 3, 1, 0, 0, 0},
    {SPAWN_POTION, 6, 3, 2, 0, 0, 0},
};
const int FIELD2_SPAWN_COUNT = (int)(sizeof(FIELD2_SPAWNS) / sizeof(FIELD2_SPAWNS[0]));
