#include "field4.h"

const int FIELD4_DATA[FIELD4_HEIGHT][MAP_W] = {
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_WALL},
    {TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_EMPTY, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL, TILE_WALL}
};

const SpawnData FIELD4_SPAWNS[] = {
    {SPAWN_DOOR, 7, 0, 0, 0, 0, 9},
    {SPAWN_DOOR, 0, 4, 0, 0, 0, -1},
    {SPAWN_DOOR, 14, 4, 0, 0, 0, 2},
    {SPAWN_DOOR, 7, 7, 0, 0, 0, 6},
    {SPAWN_OBSTACLE, 2, 2, OBSTACLE_SWITCH, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 1, OBSTACLE_ELECTRIC_WALL, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 2, OBSTACLE_ELECTRIC_WALL, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 3, OBSTACLE_ELECTRIC_WALL, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 4, OBSTACLE_ELECTRIC_WALL, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 5, OBSTACLE_ELECTRIC_WALL, 1, 0, 1},
    {SPAWN_OBSTACLE, 9, 6, OBSTACLE_ELECTRIC_WALL, 1, 0, 1}
};
const int FIELD4_SPAWN_COUNT = (int)(sizeof(FIELD4_SPAWNS) / sizeof(FIELD4_SPAWNS[0]));
